# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '12.0.11.0.1.0',
    'category': 'Studio',
    'description': u"""


This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.


""",
    'author': 'Ioppolo & Associates',
    'depends': [
        'account',
        'analytic',
        'base',
        'helpdesk',
        'helpdesk_timesheet',
        'hr_holidays',
        'hr_timesheet',
        'product',
        'project',
        'purchase',
        'timesheet_grid',
        'web_studio',
    ],
    'data': [
        'ir_model_fields.xml',
        'ir_ui_view.xml',
        'ir_actions_act_window.xml',
        'mail_template.xml',
        'ir_actions_server.xml',
        'ir_ui_menu.xml',
        'base_automation.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
